apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-demo-test
  name: spring-demo-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-demo-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-demo-test
        app.kubernetes.io/part-of: spring-demo-test
    spec:
      containers:
      - image: spring-demo-test:2.4.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15